### PR TITLE
Fix completion with allOf element

### LINKED ISSUE #2126: GenericArguments#allOf completition not working
```
CommandSpec test = CommandSpec.builder()
    .arguments(GenericArguments.allOf(GenericArguments.player(Text.of("p"))))
    .executor((src, args) -> CommandResult.success())
    .build();
Sponge.getCommandManager().register(this, test, "alloftest");
```

1. `/alloftest <tab>`
2. nothing happens

I would expect player names to appear

### PR DESCRIPTION
**Pull request by dualspiral**
Fixes #2126

@ImMorpheus please check that this works for you. I have written a couple of test commands (below) which work, but want to make sure it works with you too.

```java
        Sponge.getCommandManager().register(this.pluginContainer, CommandSpec.builder()
                .arguments(GenericArguments.allOf(GenericArguments.player(Text.of("player"))))
                .executor((src, args) -> {
                    Collection<Player> playerCollection = args.getAll("player");
                    src.sendMessage(Text.of("Selected players: ", playerCollection
                            .stream()
                            .map(User::getName)
                            .collect(Collectors.joining(", "))));
                    return CommandResult.success();
                })
                .build(), "allofplayers");

        final Collection<String> choices = ImmutableList.of("bacon", "eggs", "sausages", "beans", "spam", "sponge");
        Sponge.getCommandManager().register(this.pluginContainer, CommandSpec.builder()
                .arguments(GenericArguments.allOf(GenericArguments.choices(
                                    Text.of("choices"),
                                    () -> choices,
                                    input -> {
                                        if (choices.contains(input.toLowerCase())) {
                                            return input;
                                        }
                                        return null;
                                    }
                                )))
                .executor((src, args) -> {
                    Collection<String> playerCollection = args.getAll("choices");
                    src.sendMessage(Text.of("Selected choices: ", String.join(", ", playerCollection)));
                    return CommandResult.success();
                })
                .build(), "allofchoices");
```

### CODE REVIEW

File: src/main/java/org/spongepowered/api/command/args/CommandArgs.java [hunk 1]
```diff
@@ -65,6 +65,22 @@ public boolean hasNext() {
         return this.index + 1 < this.args.size();
     }
 
+    /**
+     * Returns true if:
+     *
+     * <ul>
+     *     <li>The next element returned by {@link #next()} is be the last</li>
```
Comment (ImMorpheus) [inline src/main/java/org/spongepowered/api/command/args/CommandArgs.java]: `is be the last` 
typo ?

**Review by ImMorpheus — APPROVED** [review]
Yup, It works

File: src/main/java/org/spongepowered/api/command/args/CommandArgs.java (hunk 1 above)
Comment (dualspiral) [reply src/main/java/org/spongepowered/api/command/args/CommandArgs.java]: Yup. It was "will be", then was meant to be "is".
